const types = {
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',

  PREV_PAGE: 'PREV_PAGE',
  NEXT_PAGE: 'NEXT_PAGE',
  PER_PAGE: 'PER_PAGE',

  SELECTED_FIELDS: 'SELECTED_FIELDS',
  GROUP_BY: 'GROUP_BY'
};

export { types };
